version: '3.3'

networks:
  openmrsdb:
  openmrsweb:
  symptommanagementdb:
services:
  toolkit-openmrs-mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./openmrs_data:/var/lib/mysql
      - ./openmrs_mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openmrs
      - MYSQL_USER=openmrs
      - MYSQL_PASSWORD=openmrs
    healthcheck:
      test: "exit 0"
    networks:
      - openmrsdb
  toolkit-openmrs-tomcat:
    image: maurya/toolkit-openmrs-tomcat:1.0
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      - toolkit-openmrs-mysql
    networks:
      - openmrsdb
      - openmrsweb
  #toolkit-openmrs-nginx:
  #  image: nginx:alpine
  #  ports:
  #    - "80:80"
  #  networks:
  #    - openmrsweb
  #    - symptommanagementdb
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #    - ./logs/access.log:/var/log/nginx/demo_access.log
  #    - ./logs/error.log:/var/log/nginx/demo_error.log
  #    - ./symptom-management:/var/www/symptom-management
  phpfpm:
    image: maurya/sm-php:7.1
    ports:
      - '9000:9000'
    volumes:
      - ./symptom-management:/var/www/symptom-management
    networks:
      - symptommanagementdb
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    networks:
      - symptommanagementdb
    volumes:
      - ./symptommanagement_data:/var/lib/mysql
      - ./symptom-management/0_meta/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symptom_management
      - MYSQL_USER=symptom_management_user
      - MYSQL_PASSWORD=maybe_its_maybelline
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    networks:
      - symptommanagementdb
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
